### PR TITLE
compillation errors fixed

### PR DESCRIPTION
**Pull request by tpimh**
This closes issue #2

### CODE REVIEW

**Comment by zesterer** [comment]
Thanks very much.

**Comment by tpimh** [comment]
Will you accept this?

**Comment by zesterer** [comment]
Merged.

**Comment by zesterer** [comment]
If you're interested, I'm recreating Nilts in 3D at my new GitHub nilts sub-domain. It'll be making a lot of use of voxel mechanics.

**Comment by tpimh** [comment]
That's an interesting project, but I will stay with Vala and Cogl for 3D graphics for now.

**Pull request merged**
